---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-3-pvc
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: vm-3-source
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Block

