---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-1-pvc
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: blank-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Block

