---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-4-pvc
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: blank
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Block

