---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fio-vm
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 4
          threads: 1
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk: {}
            - name: datadisk
              disk:
                bus: virtio
                serial: data
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.2.0
        resources:
          requests:
            memory: 20Gi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: fio-vm-pvc
        - name: datadisk
          persistentVolumeClaim:
            claimName: fio-data-pvc
        - name: cloudinit
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: ripsaw
              chpasswd: { expire: False }
              bootcmd:
                - "mkdir -p /data || true"
                - "[ -e /dev/disk/by-id/*data ] && disk=$(shopt -s nullglob; basename /dev/disk/by-id/*data) && mkfs.ext4 /dev/disk/by-id/$disk && mount /dev/disk/by-id/$disk /data"
              runcmd:
                - sed -i -e "s/PasswordAuthentication.*/PasswordAuthentication yes/" /etc/ssh/sshd_config
                - systemctl restart sshd
                - dnf install -y podman
                - img=`podman create quay.io/cloud-bulldozer/fio:latest`
                - fs=`podman mount $img`
                - mkdir -p $fs/data || true
                - mount -o bind /data $fs/data
                - chroot $fs bash -c 'cd /data; fio --version > fio.version.txt'
